server:
  port: 8080
spring:
  codec:
    max-in-memory-size: 3MB
google:
  cloud:
    access-token:
      "ya29.c.c0AY_VpZh1Te8F2mQdRacHK7gug1df77x7zabyIdu2ufzIRJbun2y9mCoQ-6iOIGPFdoU-hsE4tKrSZDBTvHNpjsZ0BDHyLlO6rIMpterE1bEbhl9fZZOiN7Q2JrHbW9bhF9bTv1ddoyfcBlqX-UlPHHg7DMpKexfG1EkDs3nXnvo2zMl0gYwggTqtTBoPkiAfw9tkkhVFFj_OVwVuRfSPH9AACxJltxeTdeKM4TBt1ebtK09_yADkWe_yRmZYhQTb0Tn9DjLxM3LbY5MZskuO_oj3v3rUZRNNmdwRNKhZa5DufZjdl9Fu8-6O-4MjmDZmIth0Bha_MHWGAQ1UMGVPbPfulfAceCt7k9bMZHa-3Svp9vMwAP2AD1YE384Dk_IrRynwq333r_gMRB6-l8byIw8Zn2sd8du5cgO03gcQhF8Fcv0RJ0-pn1SwJYw0SVwe6vinSt15vv3xmnXS6sOfUkps6xZl4M39--3J9pco3w84pjM2kXlkoqn_scRM74rgxJ2akd31t_iZf513bsaSzqvb5giB1kp62wVkw13eBlrgcVoVOuqwUl3QSdMYa_WmhsximfOwZMIhf-IuiYS9BMh0Jzot5oe1dO_ehJVFeaqtVhZnQ1diiu67vXdfXc_8gqoMa9p6quiaOlk3S6k5mqzrXFWd1h8uehp9R4v2iBp9qy9qii18pciejr4j92SsWerspyZJx50JX-2flRJMJrxpS1z_qkrs9ZUhb7RBg-Y__ijhqgc3x3g1U0SuVbMr3we26tBm7ga2n1SljkcyJxxRYjJJtfU2Y95FYIxtuoO195ebOVQkd1RQg-dd0rxOWsad9wq7817wvrhZo4JMYuizWXInX2_jp8jJQ6WX173RMXs8Icfrld1x16dxu77mm59gIftJgIJ4M8chOj8awpd6sQdzkxRiacza2sJqVSYw91zxRJ-J7yuejn-Fnc9M3vvo0Wq-w8VvZku0BUbMU_7Z7xBbFWYiX-MFooRYWsf8OB5zJFa_vWZ"
    api:
      base-url:
        "https://us-documentai.googleapis.com/v1/projects/32694591112/locations/us/processors"

