server:
  port: 8080
spring:
  codec:
    max-in-memory-size: 3MB
google:
  cloud:
    access-token:
      "ACCESS_TOKEN"
    api:
      base-url:
        "https://us-documentai.googleapis.com/v1/projects/32694591112/locations/us/processors"

digital-ocean:
  access-key: "ACCESS_KEY"
  secret-key: "SECRET-KEY"
  region: "ams3"
  end-point: "https://ams3.digitaloceanspaces.com"
  bucket-name: "tajji-kyc-documentation-bucket"



