server:
  port: 8080
spring:
  application:
    name: OCR-PIPELINE
  codec:
    max-in-memory-size: 3MB
axon:
  axon-server:
    servers: localhost:8124
  serializer:
    events: jackson
    general: jackson
    messages: jackson

google:
  cloud:
    access-token:
      "ya29.a0AfB_byCX_Sp9bATCoWt-LhMU8-7sKsXraAEfeYqdt-8dyI7uTLGIVilpkeIL_fKiCqa1X4vjCCUFP0q7y7_gt9uVV1GAzFNuN3E8dFBr3L3JjZ4_nFJjaLXbkhWK0VhPu6lgs6e3-rxwJdva6nLXTMgmQIPwIUCvuRSU1gaCgYKAVYSARASFQHGX2Mi2n9ZTsTtyCVditjfmE32Sg0173"
    api:
      base-url:
        "https://us-documentai.googleapis.com/v1/projects/32694591112/locations/us/processors"

digital-ocean:
  secret-key: "CdJgS8+eXdMDtNfoO5rQS/1lMjUZLa9rkbwe0lh8W4E"
  access-key: "DO00YJ2WUZJ98Q6QWKDG"
  region: "ams3"
  end-point: "https://ams3.digitaloceanspaces.com"
  bucket-name: "tajji-kyc-documentation-bucket"



