server:
  port: 8080
spring:
  codec:
    max-in-memory-size: 3MB
google:
  cloud:
    access-token:
      "ya29.c.c0AY_VpZh5eBdYe2Oc8MuHa_u1xUtBhyKRDScxgopAyiMXQmjFC6QROSuA870JSUXehQgMP7acGz9-L2CHwhqFiYs5YWNJl4fm-8RbwyAtgFX5nbvPDs3QbUdyO_8oJ2wBIoDthWfQRMPHmK3o9EYfiHO_Ht0CteyyW-MBlIyw3XzozlRaL6IMBKhJ7cGwx7k34FACxzsauxSZwp5opmTzpHM6c8_r2vOS-9WzR8IDmQxm1s-JjnFLY8L0jKqvPx_7m8Nf5ZpU43M2SqLlSBj5OiIKS1xQJ1R2bPayVbzMCzfl0l8GurcUUWS1-HTBTMPwUnVZocgTSAsB19klLSBH0fLWtPtQQCOO0A_9oi4ZSLnQOgMrnAWoHQG383CFeZS0oqYm8RUjrIwbMxdwJWwta0pertiq1dqkMJdf6m9tJqzyJcQjR-ckhMyw9s-rYRZtZwOu6I8lofiiO_0w_jxIzQ43VIddx7qzf9zwY4vzJh89WwQynJaMh-W8_585tIF-B8a2fUIB57r56e61j6bb43brJcmmSJlcII61x2-lzoMBlSqyOXRxnvjQ_9IMOl0k6kbqVyoovMvuwgg-F6n3x26Be5g8jlylRogBn67Rj15czeelrVp722W2mUhdk8OfR_cfQp85uXdZ8_wmOYopu_sZO4jnvtozS0IIgWj5heOMI74W6O1g0Z5_z4Y6Yze-Z_fhm260bZecumvWV-nM3JlO9UxBdg8BalQFZz6UW6diqOaVxerFjke2toZzFfFp8bjpFR0mfqOi1MqrvlwXB2gSw67lBjJt0BfS_MVJbg1hl35pO8QovuyYnlr7lUeFxmrqtvwaSteyx1o4zq8rFbUVpIRael7tpm4Zs8i58m92nVt0XUYMh1dnf4seRVcByYj9V9cnM5nopOu0myhZYYWQhkh1Jx4wVYVb0Xq3b3xbswg0B2pQ2Xu77b3MIY5glJ5lItz0hJQ6XeZ-Rz4kjaStswbIMx65vIrh88m-o5rB6sofUXMYyBp"
    api:
      base-url:
        "https://us-documentai.googleapis.com/v1/projects/32694591112/locations/us/processors"

