server:
  port: 8080
spring:
  codec:
    max-in-memory-size: 3MB
google:
  cloud:
    access-token:
      "ya29.c.c0AY_VpZh7N0lrWJghSzeGx4CEAS6hDj8zspoSuGATfr0_tqRpqLUwf2_0ka4hXtYb5zctUijGAdbQjQ0dicWFXoT58hwMyQjsKMSLPRihsb_yqDl5ZQX3yrMi8jQwYsxt2CohkfCInErH9zzyGMXYd7nMvUCoYG7vafh_NTV5rOjKJgA-VxtPHDGTo1VPdR8GI20AvTMKewo54D6uKqJ-0CyqKY0XQHjpCyZUEtlzWRSy0OWod76ZSy5ll9gRiWwtRtKlbaLZlk8pjk_mvsS42NTRE0f6fWxJl5k-AP4argQQMKO_EID3u4a7eQMewfoIy8LcoRWK2sjb5EyyFPRZGOMnYIyfk8L3GmPiT7qPu4vOqrujnqltggE383Dy9MVxzx0m61nJFSitSx2jJuhVSVYQSci263RaZkVU-SQ0tsn6wehutwelkennJWqp3JB77izr60V5gVORVVVZe559YgzkXBgRaUURBF9ZliS9Otyc8IJS7gg_3uhBtOmblYepB3pkd5OvkbI8B52m4pusx34SU3v1IBvOzc9yoZoilqZF83j9akuq1yWjxVahYd07r6xUik__iXcaZ6zg1xkrlW1O-mBlplz0hR3Vxlg7Sr7srsMXjqXQqbdmwmQgRdFOQsuWZdV-p8Sx6UbzhO4-FoVfMcb70oUgv0-68ssd8qy3juW1i2OvvviVrsUQolze31cpzuk40JflRnp4p2p9b07OtMsoIqa5dI83M6eyRstvpFl6-r32skow6wlSwmgYVMvc7qQfm6zBb0z3Xp4Xmxy4-v9R3OBxt-05MZZYJI0UJ3XiOq1oFwoOOBfhxsmq89u4j9WpQ68tp7sq5QMJwgpMzfuZzFZ6Vxju6FpRBlYOzvUkWU9m6yRnSlyBpUM2Iihi76eOkiaofXr1Rkr39Id0JioS07Sh85vi1Fx-xqem9FBJftIuRo0B3bg22VViqzqqSUynjVud2XnOrjr1n1svSwhkbjq-FVJ7wJ5teypmQz3aUkB8z7V"
    api:
      base-url:
        "https://us-documentai.googleapis.com/v1/projects/32694591112/locations/us/processors"

