server:
  port: 8080
spring:
  application:
    name: OCR-PIPELINE
  codec:
    max-in-memory-size: 3MB
axon:
  axon-server:
    servers: localhost:8124
  serializer:
    events: jackson
    general: jackson
    messages: jackson

google:
  cloud:
    access-token:
      "ya29.a0AfB_byDM7ys_Zt2bzEYqL4SJyJCXbGEAEK-37Tljj6pobh_fPql8DnJNnoMwGFx0HuAVh9FLE-Ro5hoiqME38LPT6GOXO6_IGWn099J1AjErZXKuJ0-Ofh_lA3T5IhNkB05P0vz3sDnR0u5MMjElumGCG8xyMn0GwcBACwaCgYKAWwSARASFQHGX2Mi7Hc0V6GTFu6cT-yHIN8n_g0173"
    api:
      base-url:
        "https://us-documentai.googleapis.com/v1/projects/32694591112/locations/us/processors"

digital-ocean:
  secret-key: "CdJgS8+eXdMDtNfoO5rQS/1lMjUZLa9rkbwe0lh8W4E"
  access-key: "DO00YJ2WUZJ98Q6QWKDG"
  region: "ams3"
  end-point: "https://ams3.digitaloceanspaces.com"
  bucket-name: "tajji-kyc-documentation-bucket"



